# File konfigurasi untuk Railway (Nixpacks)

[phases.setup]
# Daftar paket sistem yang perlu diinstal
aptPkgs = [
    "google-chrome-stable",
    "libgconf-2-4",
    "libx11-xcb1",
    "libxss1",
    "libasound2",
    "libnss3"
]

[start]
# Perintah untuk menjalankan aplikasi Anda
startCmd = "python main.py"
